### PR TITLE
Watchers and Forks counter

### PR DESCRIPTION
**Pull request by bernardobarreto**
Please tell me it's right this time. =]

### CODE REVIEW

**Comment by bernardobarreto** [comment]
it has been more than 2 months, could answer me please ?

**Comment by iangreenleaf** [comment]
@bernardofire it's possible his notifications aren't set up to email him about comments. Tagging @icebreaker might be a more surefire way to get his attention.

**Comment by icebreaker** [comment]
Sorry for not getting back to you earlier, this cannot be merged in as it is, because it looks horrible. If you tweak the CSS and make it look decent, I'm more than happy to merge this in.

**Comment by icebreaker** [comment]
That's OK :) writing code is like living life, not everything goes as we would like to, but that doesn't mean that we need to be pissed off.

**Pull request closed without merging**
