### PR TITLE
Support multiple badges per page

### PR DESCRIPTION
**Pull request by ahamid**
Moved badge fields to instance.

see: https://github.com/icebreaker/proudify/issues/6

### CODE REVIEW

**Comment by ahamid** [comment]
also fixed the repo limiting while i was at it

**Comment by iangreenleaf** [comment]
+1 on merging this. FWIW, when I ran into this problem I tried compiling the CoffeeScript version and this bug doesn't exist there.

**Comment by EnriqueVidal** [comment]
why don't we make the compiled version of coffescript the javascript version of proudify?

**Comment by icebreaker** [comment]
Yeah, Enrique that's my plan to switch it over + do some other "improvements". It will happen in a few days :)

**Comment by EnriqueVidal** [comment]
Awesome @icebreaker, I had some improvements in mind, but those didn't match the js code so I was waiting for you to decide on this.

**Comment by icebreaker** [comment]
I'm closing this.

**Pull request closed without merging**
